### ISSUE TITLE
Halfway through the sampling process, the picture turns all black.

### ISSUE THREAD

**Issue by liulsg** [logtd/ComfyUI-Fluxtapoz#13]
Halfway through the default workflow (the first workflow), the sample image turns black and the final image is completely black.

error message：
G:\AI\ComfyUI_w\ComfyUI\nodes.py:1506: RuntimeWarning: invalid value encountered in cast
  img = Image.fromarray(np.clip(i, 0, 255).astype(np.uint8))

**Comment by logtd** [comment]
Hi,

this appears to be an issue with your ComfyUI and not these nodes. You can open an issue with the [ComfyUI](https://github.com/comfyanonymous/ComfyUI) github to find better help there.
