### ISSUE TITLE
missing nodes

### ISSUE THREAD

**Issue by sipie800** [logtd/ComfyUI-Fluxtapoz#14]
![2024-10-20_111742](https://github.com/user-attachments/assets/0877c4b8-0b56-4ddb-8e5f-d381417b24ab)
where do I find these?

**Comment by ingtellect** [comment]
Updating comfyUI works for me.

**Comment by foxtierney** [comment]
I'm also having this issue with a fresh install of ComfyUI and these nodes installed via ComfyUI Manager.
![image](https://github.com/user-attachments/assets/21918f6f-ac60-4648-ae3c-18b0d64d0760)
