### ISSUE TITLE
这个工作流跑不动，一直卡着，其他的都能跑

### ISSUE THREAD

**Issue by atuoyi** [logtd/ComfyUI-Fluxtapoz#16]
![360截图20241020170028356](https://github.com/user-attachments/assets/8098817d-352d-4ad0-960c-3e341e849848)
![360截图20241020170054084](https://github.com/user-attachments/assets/d0eabe8c-aba1-4b0e-b7d3-a703392daa35)
![360截图202410![360截图20241020170110814](https://github.com/user-attachments/assets/29112847-a46b-41c5-aa6e-3cee40df14a5)achments/assets/afbb4833-94dc-468c-8864-cfb306c8cbc0)

**Comment by coollofty** [comment]
same problem

**Comment by logtd** [comment]
Hi, please use this workflow

https://github.com/logtd/ComfyUI-Fluxtapoz/blob/main/example_workflows/example_rf_inversion_updated.json


That workflow is for an experimental feature which is not completed.
