### ISSUE TITLE
Unable to reproduce style edit

### ISSUE THREAD

**Issue by ingtellect** [logtd/ComfyUI-Fluxtapoz#17]
Probably a noob question but I’ve been trying to reproduce the style edit of kill bill image but can't get it working. 
I used the [example workflow](https://github.com/logtd/ComfyUI-Fluxtapoz/blob/main/example_workflows/example_rf_inversion_updated.json) and only changed the image size and the prompt in the sampling as "3d disney cartoon style" or "anime style". The result image changed the face but not style. What am I missing?

3d disney cartoon style
![3d_disney_cartoon_style](https://github.com/user-attachments/assets/4c48bf49-47cd-478a-b433-3cdb57c23a77)

anime_style
![anime_style](https://github.com/user-attachments/assets/5029f026-7e8d-4ba5-8dcd-e2c16036aeed)

**Comment by logtd** [comment]
Hi! You'll need to play around with the start step, end step, and eta. Each image can require slightly different parameters

**Comment by ingtellect** [comment]
It works well. Thanks!
