### ISSUE TITLE
can i make anime into realistic?

### ISSUE THREAD

**Issue by WingeD123** [logtd/ComfyUI-Fluxtapoz#19]
there are realistic to amine examples, when i try to do the reverse, i failed.
anyone got any advise? thanks for your help

**Comment by logtd** [comment]
Here's a good start. Not exactly photo realistic. I'd try adding a controlnet and lowering the eta/steps to see if you can get more closer to what you want.

Image contains the workflow metadata.

![ComfyUI_temp_yyqhs_00098_](https://github.com/user-attachments/assets/c1ec67f8-661e-49f9-8f50-c1408db1dd9e)

**Comment by WingeD123** [comment]
> Here's a good start. Not exactly photo realistic. I'd try adding a controlnet and lowering the eta/steps to see if you can get more closer to what you want.
> 
> Image contains the workflow metadata.
> 


thanks very much. i was trying with lora. i will try something new based on your flow
