### ISSUE TITLE
The size of tensor a (8625) must match the size of tensor b (8802) at non-singleton dimension 2

### ISSUE THREAD

**Issue by guahunyo** [logtd/ComfyUI-Fluxtapoz#2]
![image](https://github.com/user-attachments/assets/d1c95c82-6012-4e8c-8175-4d18df202307)
![image](https://github.com/user-attachments/assets/d195b92c-b1f1-4329-8b7f-eb39f960b46e)

**Comment by logtd** [comment]
Looks like you're using Reference net? If so your reference image need to be the same size as the sampled image

**Comment by guahunyo** [comment]
> Looks like you're using Reference net? If so your reference image need to be the same size as the sampled image

ok  now , thank you
