### ISSUE TITLE
Unable to do young-old, man-woman

### ISSUE THREAD

**Issue by ais69** [logtd/ComfyUI-Fluxtapoz#20]
Could someone advise the correct settings to use to reproduce the  young-old, man-woman examples?

**Comment by logtd** [comment]
You can probably get better examples than these, but i've attached these images that contain the workflow. Same settings, just different prompt.

![ComfyUI_temp_yyqhs_00064_](https://github.com/user-attachments/assets/bf32953c-272c-4fb9-a83e-04748a1fa005)
![ComfyUI_temp_yyqhs_00063_](https://github.com/user-attachments/assets/5dc76bad-9422-418e-a04e-aafb7ccd03be)
