### ISSUE TITLE
Stylization with ControlNet

### ISSUE THREAD

**Issue by spiritform** [logtd/ComfyUI-Fluxtapoz#23]
is it possible to add controlnet in this workflow? would love to be able to use a depth map to guide the diffusion while referencing another image for the style. 

would be great to have a better breakdown on what Flux Reverse ODE Sampler and Outverse Flux Model Pred is doing, but mostly curious how to integrate controlnet.

![Screenshot 2024-10-22 123356](https://github.com/user-attachments/assets/a4b2cf0f-68f6-4756-b2cb-76d1b5b35f05)

**Comment by spiritform** [comment]
thanks for the reply....

really i'm just trying to pull the composition from an image and then apply a style transfer to that to try and get some consistent looking frames. 

but now i'm wondering if you even need that as a guide...  can this reference the source for composition and also change the style using another image and not just a prompt?

**Comment by logtd** [comment]
I've never tried this, but I bet with some finesse it could work:

* Unsample the image you want to style with a style prompt, e.g. "molten gold rendering" (the golden flower image example)
* Use the unsampled latents as the input to the second SamplerAdvanced
* Use the encoded style image latent (not the unsampled one) as the input to the Flux ODE Reverse node latent
* Use a controlnet on the sampler, and use an image of the composition you want, e.g. depth of a car
* Prompt for sampling should be something like "car in molten gold rendering style"

**Comment by spiritform** [comment]
ok, i'll keep at it... thank you for the reply and inspiration! super cool node.
