### ISSUE TITLE
Nodes are scattered and cannot be grouped under the same menu item

### ISSUE THREAD

**Issue by Tanglinling** [logtd/ComfyUI-Fluxtapoz#28]
As shown in the figure, I couldn't find them without the sample workflow, and now I'm not sure I've found all the nodes.
![image](https://github.com/user-attachments/assets/48d6296d-9fde-4ebd-b6ab-66570aa38d55)
![image](https://github.com/user-attachments/assets/e296db75-08bc-44ba-b972-97202c5095c0)
![image](https://github.com/user-attachments/assets/75f534e7-69d9-4738-94cf-6cc18d78612f)

**Comment by logtd** [comment]
All nodes are now in "fluxtapoz" category in the latest update. Thanks for calling this to my attention!
