### ISSUE TITLE
how to combine rf-inversion + rave + flatten for flux based temporally consistent frames

### ISSUE THREAD

**Issue by biswaroop1547** [logtd/ComfyUI-Fluxtapoz#31]
Super grateful for your work!
I recently came across [this](https://x.com/logtdx/status/1847353040963035365) tweet of yours, and super interested on how can I make use of the nodes present here to get to something which will take an input video then use rf-inversion, rave and flatten to make such stabilized consistent frames. I am able to use rf-inversion properly but that's not enough for temporal consistency. So for flux how can I combine these three techniques, if you can guide a bit then it'd be awesome!

Also keep up the great work 🚀

**Comment by logtd** [comment]
Hey, I haven't made that code "public", since I don't want to maintain it.

However the code does exist in this repo and it just needs to be turned on. I wasn't happy with the results and personally think that video models have progressed enough to where we can use this effectively

**Comment by biswaroop1547** [comment]
Thanks for your response!
I see, so @logtd currently what I am trying to do is I have flux based loras trained on a specific character that I want to animate (much harder physics than human), with a pipeline as such using rave + rf-inversion+ flatten would be super helpful for me to actually be able to animate and have high control. On animatediff me and my colleagues have spent quite some time and didn't feel the results are upto par, this looked quite nice and better to be honest so it would be super helpful if you could tell me how should I proceed on connecting these three things?

> personally think that video models have progressed enough to where we can use them effectively instead of image models
Currently using video models I am only able to do img2vid, frame interpolation etc. But that actually doesn't help on giving you actual control to animate any of your personal characters with consistency on physics (who's only 10-15 images you have on how the character looks).

> However the code does exist in this repo and it just needs to be turned on
My current knowledge is limited but I am trying to understand how flatten and rave works so that I can use it with rf-inversion
I did get some starting help from [this](https://github.com/raven38/rf_inversion) repo on rf-inversion + your this repo too, but a bit stuck on how to combine flatten and rave with it.

**Comment by logtd** [comment]
Ah, I see.

There's been some interest in me publishing these nodes for Flux officially, and I may do so in another repo (so that it's not confusing for people using rf-inversion).

I've been experimenting with using Flux for images and then using an image 2 video model (CogVideoX) with some techniques that I haven't released yet (they're not ready) that force Cog to follow an input video exactly. Hopefully I can get some time to finish those because the early results are very impressive. They just don't always follow the input video exactly yet. Stay tuned

This example shows an image made with Flux from the first frame of the video, then the video is driven by CogX

https://github.com/user-attachments/assets/b4c2517d-eec6-4d92-93a6-f8dc077a639b

**Comment by biswaroop1547** [comment]
This looks very promising! Runway's Act-1 vibes!
 Sorry for the late response for some reason I didn't get the notif 😞
 
@logtd for my specific case I don't think it'll handle all because for my character the physical attributes is quite different (alien-like) which no model has ever seen before so if we let a video model drive the generation then the physics would be slightly biased towards its training data, hence I was so interested in able to use a finetuned flux lora (or video lora possibly, but for that we need videos first - so deadlock) to guide the generation frames while somehow keeping them temporally consistent.

Would highly help to know what you think about this 🙏🏻
