### ISSUE TITLE
Inverts reference style images still need to require text descriptions of the images

### ISSUE THREAD

**Issue by ziyaxuanyi** [logtd/ComfyUI-Fluxtapoz#32]
Inverts reference style images still need to require text descriptions of the images, but the paper said it doesn't need text descriptions of the images.
If there is no text descriptions of the images, the result become very bad

**Comment by DarkMnDragon** [comment]
Exactly, this is how it is expected to perform

**Comment by logtd** [comment]
rf-inversion uses an inversion prompt when styling 
> Stylization using a single reference image and various text prompts. Given a reference style image (e.g. “melting golden 3d rendering” at the top) and various text prompts (e.g. “a dwarf in melting golden 3d rendering style”), our method generates images that are consistent with the reference style image and aligned with the given text prompt.

but it does not use an inversion prompt when editing.

**Comment by DarkMnDragon** [comment]
So the inversion process we need null prompt, but when performing editing we need to use the style prompt

**Comment by logtd** [comment]
It depends what you're trying to do with RF-Inversion. The two basic tasks are image editing and image stylization. Check out the project page for a good idea of the two: https://rf-inversion.github.io/

For image editing, you do not need an inversion prompt. You just want to use a prompt of whatever you want to edit. So if you want to make the man a cartoon man, you'd prompt `cartoon man`.

For stylization, you need an inversion prompt of the style, e.g. `molten golden rendering`. Then in the sampling prompt, if you wanted to make a dragon in that style, you'd prompt `dragon in the style of molden gold rendering`.

You have to play with eta/end_start/start_step for different images and what you're looking for, there's not a one size fits all.

**Comment by ziyaxuanyi** [comment]
> 您好，感谢您的关注。
> 
> RF-Inversion 在造型时使用反转提示
> 
> > 使用单个参考图像和各种文本提示的样式化。给定参考样式图像（例如顶部的 “melting golden 3d rendering”）和各种文本提示（例如 “a dwarf in melting golden 3d rendering style”），我们的方法生成的图像与参考样式图像一致，并与给定的文本提示对齐。
> 
> 但在编辑时不使用反转提示。
> 
> 如果论文中有一个段落不是这样，请把它粘贴到这里。

Yes, the paragraph you provided comes from the final appendix content, and as you said.
But at the beginning of the paper, there is such a description that I don't quite understand the meaning here. It seems to be exactly what I described.
![impicture_20241101_154953](https://github.com/user-attachments/assets/e71f1d79-9f27-4a40-8729-5fd0a683ef2d)

By the way, if inverts reference style images still need to the text descriptions of the images, so it will have huge limitations in use, after all, there are a large number of image styles that we cannot accurately describe in natural language and even we don't know how to describe the style
