### ISSUE TITLE
oom when using gguf flux 

### ISSUE THREAD

**Issue by jesenzhang** [logtd/ComfyUI-Fluxtapoz#33]
![image](https://github.com/user-attachments/assets/8064d1fd-3967-493f-b254-c4bab41d1ca6)
when using this for chekpoint,got 

torch.OutOfMemoryError: Allocation on device 
Got an OOM, unloading all loaded models.

used the example_rf_inversion_workflow.json workflow

**Comment by logtd** [comment]
Hi, this looks to be an issue with ComfyUI and not these nodes.
Please open an issue on their github
