### ISSUE TITLE
flux

### ISSUE THREAD

**Issue by meta10110** [logtd/ComfyUI-Fluxtapoz#39]
Thanks for sharing,Here are some of my little doubts:
What is the specific function of this node? I'm not very familiar with the source code. When I try to reduce the guidence value to make the output image less greasy and less realistic, I find that adjusting it to zero or a negative number has no effect on the generated result.
![image](https://github.com/user-attachments/assets/0df886bf-b435-46b5-a3cc-9220cfefdd6a)

**Comment by NitishTRI3D** [comment]
I think it's same as flux guidance , it was just named deguidance

**Comment by meta10110** [comment]
> I think it's same as flux guidance , it was just named deguidance

thanks for the reply,i'll try to figure it out.

**Comment by logtd** [comment]
it just lets you change guidance below 0 for testing purposes. No specific value or function
