### ISSUE TITLE
rf inversion flux normal checkpoint loader?

### ISSUE THREAD

**Issue by bramvera** [logtd/ComfyUI-Fluxtapoz#4]
In the RF inversion workflow, is the sample checkpoint loader supposed to load the flux model using the normal loader instead of U-Net?
![image](https://github.com/user-attachments/assets/995ecd7e-5591-4bec-9a91-ccdbda694dc2)

**Comment by skydam** [comment]
I don't understand this either. It immediately throws an error, even when i use DualCLIPLoader and Load VAE to set the CLIP and VAE.

**Comment by bramvera** [comment]
> I don't understand this either. It immediately throws an error, even when i use DualCLIPLoader and Load VAE to set the CLIP and VAE.

try this:
![image](https://github.com/user-attachments/assets/96299a80-b204-4b27-a23c-4f5fc42b3843)

**Comment by logtd** [comment]
Ah, sorry about that folks. I started the workflow from the base Comfy example on FP8 Flux
https://comfyanonymous.github.io/ComfyUI_examples/flux/#simple-to-use-fp8-checkpoint-version

Seems like this is uncommon and i'll use the other way in future updates
