### ISSUE TITLE
Plans to integrate RF Solver Edit into these nodes ?

### ISSUE THREAD

**Issue by NitishTRI3D** [logtd/ComfyUI-Fluxtapoz#40]
https://github.com/wangjiangshan0725/RF-Solver-Edit

Seems superior to RF-Inversion

**Comment by tuckerdarby** [comment]
I could do the flux implementation when I get time

**Comment by logtd** [comment]
potentially the flux implementation when I get time

**Comment by NitishTRI3D** [comment]
RF-Solver-Edit is a spin off of flux inference implementation after looking at the code base structure. They made changes to denoise function by passing info dictionary. 

So you want to implement flux original codebase in ComfyUI, is that what you meant by "flux implementation" ?

**Comment by logtd** [comment]
They did a flux and open sora (for video) implementation. I don't plan to do anything for open sora at this time

**Comment by NitishTRI3D** [comment]
Okay that way, got it! 
I can help in benchmarking/testing existing rf inversion vs rf-solver-edit

**Comment by logtd** [comment]
Great, if I have time this weekend i'll look into it

**Comment by logtd** [comment]
![ComfyUI_temp_pzybb_00005_](https://github.com/user-attachments/assets/cfae98de-9fa4-47de-81d2-21a7bd17f114)


it's been added. Feel free to test, there's an example workflow in the directory too

**Comment by NitishTRI3D** [comment]
Not sure what to make of this , I tried the same example with your older workflow , it also seems to achieve the change directionally, but tough to conclusively say it improved. 

![ComfyUI_temp_rujao_00014_](https://github.com/user-attachments/assets/a8291848-621e-43dd-baa2-2ca1d8002a98)

Tried with garment changing usecase that I am looking at, but nothing very controllable to rely on. 

 I was reading some reddit post where people were saying diffusion model inversion is unstable where as rectified flow inversion because of the architecture is more suitable. Are there any production usecases that are being tackled with rf inversion ?

**Comment by logtd** [comment]
I didn't find it that great to be honest. There's another workflow that differs from the official repo's way of doing it that I had much better results though -- I can upload that when I get time. 

RF-Inversion/RF-Edit have much more stable inversion and reconstruction. In terms of production use cases it'll heavily depend on what you want to expose to users as it's not a one setting fits all.

**Comment by NitishTRI3D** [comment]
Hey sure. Please upload the workflow. Would like to check that out.

**Comment by wangjiangshan0725** [comment]
@logtd Thanks for your implementation of our method (RF-Solver). Could you add our work into the acknowledgement in the Readme of this repo? (the url of our original repo is https://github.com/wangjiangshan0725/RF-Solver-Edit) Thanks!

**Comment by logtd** [comment]
Hi @wangjiangshan0725, thanks for your research! 

I've added your acknowledgement to the readme and am planning on adding a section just for RF-Edit when I get some time.

**Comment by drphero** [comment]
@logtd When trying either of your rf-edit workflows with the same horse archery image, both stages output just black. I think it has something to do with the Configure Modified Flux node because when removing that and reloading the flux model, it creates an output but of course not with the desired result (it has more changes). The original rf inversion method works fine as well. 

There are no errors in the terminal, just this:

```
double_block 0 modified
double_block 1 modified
double_block 2 modified
double_block 3 modified
double_block 4 modified
double_block 5 modified
double_block 6 modified
double_block 7 modified
double_block 8 modified
double_block 9 modified
double_block 10 modified
double_block 11 modified
double_block 12 modified
double_block 13 modified
double_block 14 modified
double_block 15 modified
double_block 16 modified
double_block 17 modified
double_block 18 modified
single_block 0 modified
single_block 1 modified
single_block 2 modified
single_block 3 modified
single_block 4 modified
single_block 5 modified
single_block 6 modified
single_block 7 modified
single_block 8 modified
single_block 9 modified
single_block 10 modified
single_block 11 modified
single_block 12 modified
single_block 13 modified
single_block 14 modified
single_block 15 modified
single_block 16 modified
single_block 17 modified
single_block 18 modified
single_block 19 modified
single_block 20 modified
single_block 21 modified
single_block 22 modified
single_block 23 modified
single_block 24 modified
single_block 25 modified
single_block 26 modified
single_block 27 modified
single_block 28 modified
single_block 29 modified
single_block 30 modified
single_block 31 modified
single_block 32 modified
single_block 33 modified
single_block 34 modified
single_block 35 modified
single_block 36 modified
single_block 37 modified
```

**Comment by logtd** [comment]
@NitishTRI3D here's the alternate rf-edit workflow https://github.com/logtd/ComfyUI-Fluxtapoz/blob/main/example_workflows/example_rf_edit_workflow_alternative.json

@drphero thanks for the notice. I'll take a look when I get time

**Comment by fisj** [comment]
I'm also very interested in RFEdit with this. How would one vary the seed each generation with this alternative workflow?

**Comment by logtd** [comment]
@fisj there's no randomness involved with RF-Edit so there's no seed. You can try changing the prompt, etc.
