### ISSUE TITLE
It's weird, why are all the images I generate undenoised?

### ISSUE THREAD

**Issue by 0002kgHg** [logtd/ComfyUI-Fluxtapoz#43]
![workflow](https://github.com/user-attachments/assets/77ea9ebb-762a-4695-81bf-f09622c68828)

**Comment by logtd** [comment]
Hey, thanks for your interest.

Please use the example workflow https://github.com/logtd/ComfyUI-Fluxtapoz/blob/main/example_workflows/example_rf_inversion_updated.json

Unfortunately I don't have time to debug changed workflows.

Or take a look at a few tutorial videos that have been made:
* https://www.youtube.com/watch?v=ozd9yDk6JTE
* https://www.youtube.com/watch?v=-qVDWE0A1ek

**Comment by logtd** [comment]
I'll leave this open though in case someone has time to help you
