### ISSUE TITLE
FlowEdit Sampler

### ISSUE THREAD

**Issue by Amazon90** [logtd/ComfyUI-Fluxtapoz#46]
Hello, author. I have carefully compared the two workflows, example_rf_inversion_stylization.json and example_rf_edit_workflow_alternative.json. The latter replaces the FluxForwardODESampler and FluxReverseODESampler nodes used in the former with the FlowEditForwardSampler and FlowEditReverseSampler nodes. However, in my usage, I still cannot figure out the following questions and hope you can provide answers.
Should the save_steps value in the FlowEditForwardSampler node be consistent with the steps in the BasicScheduler node?
In my attempts, the inject_steps value in the FlowEditReverseSampler node does not change the results regardless of the value used.
![3](https://github.com/user-attachments/assets/c138704a-7c4e-42c2-8bf3-bf1d06c41062)
![1](https://github.com/user-attachments/assets/371e62b4-aac2-4510-8f84-297deb737bb0)
![2](https://github.com/user-attachments/assets/6d631ad8-979e-4ced-9d23-ccd96381bee5)

**Comment by logtd** [comment]
Hi, thanks for your interest.

The `example_rf_inversion_stylization.json` workflow is using for stylizing and not editing images, so that one will have very different results than the RF-Edit workflow. [This workflow](https://github.com/logtd/ComfyUI-Fluxtapoz/blob/main/example_workflows/example_rf_inversion_updated.json) is used for editing using RF-Inversion.

In your RF-Edit example above, it looks like you are missing the `Configure Modified Flux` node that should be placed immediately after loading a model. Otherwise the model can't inject the saved information from the forward (unsampling) part.

**Comment by Amazon90** [comment]
> Hi, thanks for your interest.
> 
> 
> 
> The `example_rf_inversion_stylization.json` workflow is using for stylizing and not editing images, so that one will have very different results than the RF-Edit workflow. [This workflow](https://github.com/logtd/ComfyUI-Fluxtapoz/blob/main/example_workflows/example_rf_inversion_updated.json) is used for editing using RF-Inversion.
> 
> 
> 
> In your RF-Edit example above, it looks like you are missing the `Configure Modified Flux` node that should be placed immediately after loading a model. Otherwise the model can't inject the saved information from the forward (unsampling) part.

Thank you so much for your contribution and for patiently addressing my questions. I will carefully review the example workflow you provided again. Please forgive me for modifying some of the node connections for my understanding.

**Comment by Amazon90** [comment]
> Hi, thanks for your interest.
> 
> The `example_rf_inversion_stylization.json` workflow is using for stylizing and not editing images, so that one will have very different results than the RF-Edit workflow. [This workflow](https://github.com/logtd/ComfyUI-Fluxtapoz/blob/main/example_workflows/example_rf_inversion_updated.json) is used for editing using RF-Inversion.
> 
> In your RF-Edit example above, it looks like you are missing the `Configure Modified Flux` node that should be placed immediately after loading a model. Otherwise the model can't inject the saved information from the forward (unsampling) part.

After incorporating the Configure Modified Flux node into the model pipeline, the rf editor workflow is now functioning properly. Thank you.
