### ISSUE TITLE
Do you plan on adding the FluxSDE Sampler node aswell?

### ISSUE THREAD

**Issue by BadisG** [logtd/ComfyUI-Fluxtapoz#5]
Hello,

On their blog page, we can see that they managed to make a SDE sampler that works on Flux. It would be interesting to implement that aswell.
https://rf-inversion.github.io/
![image](https://github.com/user-attachments/assets/bcfca695-8d9d-4cd8-872e-b000709e096a)

**Comment by logtd** [comment]
Yep, probably by the end of the week
