### ISSUE TITLE
The generated output is blurry.

### ISSUE THREAD

**Issue by za-wa-n-go** [logtd/ComfyUI-Fluxtapoz#6]
![image](https://github.com/user-attachments/assets/950383c7-907c-4cb5-babe-cfba6ccb07cd)
It also feels like it's turned into i2i.
I entered the prompt "a boy" along with the attached image, but I didn't see any noticeable changes.
I don't think I did anything different besides the prompt.

**Comment by logtd** [comment]
Hey, you'll have to do some experimenting with the start_step, end_step, and Eta on the sampler to get your desired results. It should be possible!
