### ISSUE TITLE
Deterministic results

### ISSUE THREAD

**Issue by rrroddri** [logtd/ComfyUI-Fluxtapoz#8]
Hey, thank you so much for this implementation of RF Inversion. Is there a way to push deterministic results? I tried to use a fixed seed noise, but once I reloaded the workflow, it still gives me a different result. 

I'm using the stylization updated workflow

Thank you in advance

**Comment by logtd** [comment]
Hey, thanks for your interest!

I've added a seed to the Forward ODE sampler that was likely causing indeterministic results. Also an updated workflow.

Let me know if your issues still continue and feel free to reopen this issue.

**Comment by rrroddri** [comment]
Thank you so much! Hope you have a great day
